resume:
pretrain:
seed: 0
data:
    dataset: k400
    modality: RGB
    num_segments: 16
    seg_length: 1
    batch_size: 1
    workers: 2
    num_classes: 400
    image_tmpl: 'img_{:05d}.jpg'
    train_root: '/media/ssd8T/kinetics400/k400img'
    train_list: '/media/ssd8T/CLIP_TSM6/lists/k400/train_videofolder.txt' #'lists/k400/kinetics_rgb_train_se320.txt' 
    val_root: /media/ssd8T/kinetics400/k400img
    val_list: /media/ssd8T/CLIP_TSM6/lists/k400/val_videofolder.txt #'/media/ssd8T/CLIP_TSM/lists/k400/1_10_val_videofolder.txt' #'/media/ssd8T/CLIP_TSM6/lists/k400/val_videofolder.txt' #lists/k400/kinetics_rgb_val_se320.txt
    label_list: '/media/ssd8T/CLIP_TSM6/lists/k400/kinetics_400_labels.csv'
    input_size: 224
    random_shift: True
    output_path: exps
network:
    arch: ViT-B/16  #ViT-B/32 ViT-B/16
    init: True
    tm: False
    drop_out: 0.0 
    emb_dropout: 0.0 
    sim_header: Transf  # Transf   None  
    interaction: VCS  # DP VCS
    joint_st: False
    drop: 0           
    fix_text: True  
    fix_video: False        
solver:
    type: cosine
    epochs: 30
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-5
    lr_warmup_step: 5
    weight_decay: 0.2
    loss_type: NCE
    evaluate: False
    clip_ratio: 0.1
    grad_accumulation_steps: 1
logging:
    print_freq: 10
    eval_freq: 1