resume:
pretrain:
seed: 0
data:
    dataset: kinetics600
    modality: video
    num_segments: 16
    seg_length: 1
    batch_size: 1
    workers: 2
    num_classes: 160
    image_tmpl: 'img_{:05d}.jpg'
    val_root: /media/ssd8T/kinetics600/k600/test
    val_list:  /media/ssd8T/BIKE/lists/k600/test_split1_exist.txt #'/media/ssd8T/CLIP_TSM/lists/k400/1_10_val_videofolder.txt' #'/media/ssd8T/CLIP_TSM6/lists/k400/val_videofolder.txt' #lists/k400/kinetics_rgb_val_se320.txt
    label_list: '/media/ssd8T/BIKE/lists/k600/k160_labels_split1.csv' #'/media/ssd8T/TPT-video/calibration/neutral_labels_ucf101.csv' #'/media/ssd8T/UCF101/annotations/ucf_labels.csv'
    input_size: 224
    random_shift: True
    output_path: exps
network:
    arch: ViT-B/16  #ViT-B/32 ViT-B/16
    init: True
    tm: False
    drop_out: 0.0 
    emb_dropout: 0.0 
    sim_header: Transf  # Transf   None  
    interaction: VCS  # DP VCS
    joint_st: False
    drop: 0           
    fix_text: True  
    fix_video: False    
    network: 1
solver:
    type: cosine
    epochs: 30
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-5
    lr_warmup_step: 5
    weight_decay: 0.2
    loss_type: NCE
    evaluate: False
    clip_ratio: 0.1
    grad_accumulation_steps: 1
logging:
    print_freq: 10
    eval_freq: 1